# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="indexer.proto",
    package="protos",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=b'\n\rindexer.proto\x12\x06protos"$\n\x05Order\x12\x1b\n\x05items\x18\x01 \x03(\x0e\x32\x0c.protos.Item"\x16\n\x05\x43heck\x12\r\n\x05total\x18\x01 \x01(\x01*#\n\x04Item\x12\x08\n\x04SPAM\x10\x00\x12\x08\n\x04\x45GGS\x10\x01\x12\x07\n\x03HAM\x10\x02\x32\x30\n\x07Indexer\x12%\n\x03\x45\x61t\x12\r.protos.Order\x1a\r.protos.Check"\x00\x62\x06proto3',
)

_ITEM = _descriptor.EnumDescriptor(
    name="Item",
    full_name="protos.Item",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="SPAM", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="EGGS", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="HAM", index=2, number=2, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=87,
    serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_ITEM)

Item = enum_type_wrapper.EnumTypeWrapper(_ITEM)
SPAM = 0
EGGS = 1
HAM = 2


_ORDER = _descriptor.Descriptor(
    name="Order",
    full_name="protos.Order",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="items",
            full_name="protos.Order.items",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=25,
    serialized_end=61,
)


_CHECK = _descriptor.Descriptor(
    name="Check",
    full_name="protos.Check",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="total",
            full_name="protos.Check.total",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=63,
    serialized_end=85,
)

_ORDER.fields_by_name["items"].enum_type = _ITEM
DESCRIPTOR.message_types_by_name["Order"] = _ORDER
DESCRIPTOR.message_types_by_name["Check"] = _CHECK
DESCRIPTOR.enum_types_by_name["Item"] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Order = _reflection.GeneratedProtocolMessageType(
    "Order",
    (_message.Message,),
    {
        "DESCRIPTOR": _ORDER,
        "__module__": "indexer_pb2"
        # @@protoc_insertion_point(class_scope:protos.Order)
    },
)
_sym_db.RegisterMessage(Order)

Check = _reflection.GeneratedProtocolMessageType(
    "Check",
    (_message.Message,),
    {
        "DESCRIPTOR": _CHECK,
        "__module__": "indexer_pb2"
        # @@protoc_insertion_point(class_scope:protos.Check)
    },
)
_sym_db.RegisterMessage(Check)


_INDEXER = _descriptor.ServiceDescriptor(
    name="Indexer",
    full_name="protos.Indexer",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=124,
    serialized_end=172,
    methods=[
        _descriptor.MethodDescriptor(
            name="Eat",
            full_name="protos.Indexer.Eat",
            index=0,
            containing_service=None,
            input_type=_ORDER,
            output_type=_CHECK,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_INDEXER)

DESCRIPTOR.services_by_name["Indexer"] = _INDEXER

# @@protoc_insertion_point(module_scope)
