# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='indexer.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rindexer.proto\x12\x06protos\x1a\x0c\x63ommon.proto\"\"\n\x14InsertSegmentRequest\x12\n\n\x02id\x18\x01 \x01(\t2I\n\x07Indexer\x12>\n\rInsertSegment\x12\x1c.protos.InsertSegmentRequest\x1a\r.protos.Error\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_INSERTSEGMENTREQUEST = _descriptor.Descriptor(
  name='InsertSegmentRequest',
  full_name='protos.InsertSegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protos.InsertSegmentRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['InsertSegmentRequest'] = _INSERTSEGMENTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InsertSegmentRequest = _reflection.GeneratedProtocolMessageType('InsertSegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTSEGMENTREQUEST,
  '__module__' : 'indexer_pb2'
  # @@protoc_insertion_point(class_scope:protos.InsertSegmentRequest)
  })
_sym_db.RegisterMessage(InsertSegmentRequest)



_INDEXER = _descriptor.ServiceDescriptor(
  name='Indexer',
  full_name='protos.Indexer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='InsertSegment',
    full_name='protos.Indexer.InsertSegment',
    index=0,
    containing_service=None,
    input_type=_INSERTSEGMENTREQUEST,
    output_type=common__pb2._ERROR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INDEXER)

DESCRIPTOR.services_by_name['Indexer'] = _INDEXER

# @@protoc_insertion_point(module_scope)
