# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import common_pb2 as common__pb2
import storage_pb2 as storage__pb2


class StorageStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Configure = channel.unary_unary(
                '/protos.Storage/Configure',
                request_serializer=storage__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=common__pb2.Error.FromString,
                )
        self.Insert = channel.unary_unary(
                '/protos.Storage/Insert',
                request_serializer=storage__pb2.InsertRequest.SerializeToString,
                response_deserializer=common__pb2.Error.FromString,
                )
        self.Segment = channel.unary_unary(
                '/protos.Storage/Segment',
                request_serializer=storage__pb2.SegmentRequest.SerializeToString,
                response_deserializer=storage__pb2.SegmentResponse.FromString,
                )
        self.Segments = channel.unary_unary(
                '/protos.Storage/Segments',
                request_serializer=storage__pb2.SegmentsRequest.SerializeToString,
                response_deserializer=storage__pb2.SegmentsResponse.FromString,
                )


class StorageServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Segment(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Segments(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=storage__pb2.ConfigureRequest.FromString,
                    response_serializer=common__pb2.Error.SerializeToString,
            ),
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=storage__pb2.InsertRequest.FromString,
                    response_serializer=common__pb2.Error.SerializeToString,
            ),
            'Segment': grpc.unary_unary_rpc_method_handler(
                    servicer.Segment,
                    request_deserializer=storage__pb2.SegmentRequest.FromString,
                    response_serializer=storage__pb2.SegmentResponse.SerializeToString,
            ),
            'Segments': grpc.unary_unary_rpc_method_handler(
                    servicer.Segments,
                    request_deserializer=storage__pb2.SegmentsRequest.FromString,
                    response_serializer=storage__pb2.SegmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Storage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Storage(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/Configure',
            storage__pb2.ConfigureRequest.SerializeToString,
            common__pb2.Error.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/Insert',
            storage__pb2.InsertRequest.SerializeToString,
            common__pb2.Error.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Segment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/Segment',
            storage__pb2.SegmentRequest.SerializeToString,
            storage__pb2.SegmentResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Segments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/Segments',
            storage__pb2.SegmentsRequest.SerializeToString,
            storage__pb2.SegmentsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
