# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gallop.protos.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='coordinator.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x63oordinator.proto\x12\x06protos\x1a\x0c\x63ommon.proto\"8\n\x04Node\x12\"\n\x08nodeType\x18\x01 \x01(\x0e\x32\x10.protos.NodeType\x12\x0c\n\x04host\x18\x02 \x01(\t\")\n\x0bNodeRequest\x12\x1a\n\x04node\x18\x01 \x01(\x0b\x32\x0c.protos.Node\".\n\x0f\x43lusterResponse\x12\x1b\n\x05nodes\x18\x01 \x03(\x0b\x32\x0c.protos.Node\"\x10\n\x0e\x43lusterRequest*4\n\x08NodeType\x12\x0b\n\x07INDEXER\x10\x00\x12\n\n\x06PACKER\x10\x01\x12\x0f\n\x0b\x43OORDINATOR\x10\x02\x32}\n\x0b\x43oordinator\x12<\n\x07\x43luster\x12\x16.protos.ClusterRequest\x1a\x17.protos.ClusterResponse\"\x00\x12\x30\n\x08Register\x12\x13.protos.NodeRequest\x1a\r.protos.Error\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_NODETYPE = _descriptor.EnumDescriptor(
  name='NodeType',
  full_name='protos.NodeType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INDEXER', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PACKER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COORDINATOR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=210,
  serialized_end=262,
)
_sym_db.RegisterEnumDescriptor(_NODETYPE)

NodeType = enum_type_wrapper.EnumTypeWrapper(_NODETYPE)
INDEXER = 0
PACKER = 1
COORDINATOR = 2



_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='protos.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeType', full_name='protos.Node.nodeType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host', full_name='protos.Node.host', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=99,
)


_NODEREQUEST = _descriptor.Descriptor(
  name='NodeRequest',
  full_name='protos.NodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='protos.NodeRequest.node', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=142,
)


_CLUSTERRESPONSE = _descriptor.Descriptor(
  name='ClusterResponse',
  full_name='protos.ClusterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='protos.ClusterResponse.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=190,
)


_CLUSTERREQUEST = _descriptor.Descriptor(
  name='ClusterRequest',
  full_name='protos.ClusterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=208,
)

_NODE.fields_by_name['nodeType'].enum_type = _NODETYPE
_NODEREQUEST.fields_by_name['node'].message_type = _NODE
_CLUSTERRESPONSE.fields_by_name['nodes'].message_type = _NODE
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['NodeRequest'] = _NODEREQUEST
DESCRIPTOR.message_types_by_name['ClusterResponse'] = _CLUSTERRESPONSE
DESCRIPTOR.message_types_by_name['ClusterRequest'] = _CLUSTERREQUEST
DESCRIPTOR.enum_types_by_name['NodeType'] = _NODETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:protos.Node)
  })
_sym_db.RegisterMessage(Node)

NodeRequest = _reflection.GeneratedProtocolMessageType('NodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _NODEREQUEST,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:protos.NodeRequest)
  })
_sym_db.RegisterMessage(NodeRequest)

ClusterResponse = _reflection.GeneratedProtocolMessageType('ClusterResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERRESPONSE,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:protos.ClusterResponse)
  })
_sym_db.RegisterMessage(ClusterResponse)

ClusterRequest = _reflection.GeneratedProtocolMessageType('ClusterRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERREQUEST,
  '__module__' : 'coordinator_pb2'
  # @@protoc_insertion_point(class_scope:protos.ClusterRequest)
  })
_sym_db.RegisterMessage(ClusterRequest)



_COORDINATOR = _descriptor.ServiceDescriptor(
  name='Coordinator',
  full_name='protos.Coordinator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=264,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='Cluster',
    full_name='protos.Coordinator.Cluster',
    index=0,
    containing_service=None,
    input_type=_CLUSTERREQUEST,
    output_type=_CLUSTERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='protos.Coordinator.Register',
    index=1,
    containing_service=None,
    input_type=_NODEREQUEST,
    output_type=common__pb2._ERROR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COORDINATOR)

DESCRIPTOR.services_by_name['Coordinator'] = _COORDINATOR

# @@protoc_insertion_point(module_scope)
