# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gallop.protos.common_pb2 as common__pb2
import gallop.protos.coordinator_pb2 as coordinator__pb2


class CoordinatorStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Cluster = channel.unary_unary(
                '/protos.Coordinator/Cluster',
                request_serializer=coordinator__pb2.ClusterRequest.SerializeToString,
                response_deserializer=coordinator__pb2.ClusterResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/protos.Coordinator/Register',
                request_serializer=coordinator__pb2.NodeRequest.SerializeToString,
                response_deserializer=common__pb2.Error.FromString,
                )


class CoordinatorServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=coordinator__pb2.ClusterRequest.FromString,
                    response_serializer=coordinator__pb2.ClusterResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=coordinator__pb2.NodeRequest.FromString,
                    response_serializer=common__pb2.Error.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Coordinator/Cluster',
            coordinator__pb2.ClusterRequest.SerializeToString,
            coordinator__pb2.ClusterResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Coordinator/Register',
            coordinator__pb2.NodeRequest.SerializeToString,
            common__pb2.Error.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
