# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='packer.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cpacker.proto\x12\x06protos\x1a\x0c\x63ommon.proto\"7\n\x0eSegmentRequest\x12%\n\nsegment_id\x18\x01 \x01(\x0b\x32\x11.protos.SegmentId\"3\n\x0fSegmentResponse\x12 \n\x07segment\x18\x01 \x01(\x0b\x32\x0f.protos.Segment\"\x11\n\x0fSegmentsRequest\"7\n\x10SegmentsResponse\x12#\n\x08segments\x18\x02 \x03(\x0b\x32\x11.protos.SegmentId\"1\n\x10\x43onfigureRequest\x12\x1d\n\x06tables\x18\x01 \x03(\x0b\x32\r.protos.Table\"8\n\rInsertRequest\x12\r\n\x05table\x18\x01 \x01(\t\x12\x18\n\x03row\x18\x02 \x01(\x0b\x32\x0b.protos.Row2\xb9\x01\n\x06Packer\x12\x30\n\x06Insert\x12\x15.protos.InsertRequest\x1a\r.protos.Error\"\x00\x12<\n\x07Segment\x12\x16.protos.SegmentRequest\x1a\x17.protos.SegmentResponse\"\x00\x12?\n\x08Segments\x12\x17.protos.SegmentsRequest\x1a\x18.protos.SegmentsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_SEGMENTREQUEST = _descriptor.Descriptor(
  name='SegmentRequest',
  full_name='protos.SegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='protos.SegmentRequest.segment_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=93,
)


_SEGMENTRESPONSE = _descriptor.Descriptor(
  name='SegmentResponse',
  full_name='protos.SegmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='protos.SegmentResponse.segment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=146,
)


_SEGMENTSREQUEST = _descriptor.Descriptor(
  name='SegmentsRequest',
  full_name='protos.SegmentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=165,
)


_SEGMENTSRESPONSE = _descriptor.Descriptor(
  name='SegmentsResponse',
  full_name='protos.SegmentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='protos.SegmentsResponse.segments', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=222,
)


_CONFIGUREREQUEST = _descriptor.Descriptor(
  name='ConfigureRequest',
  full_name='protos.ConfigureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tables', full_name='protos.ConfigureRequest.tables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=273,
)


_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='protos.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='protos.InsertRequest.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='protos.InsertRequest.row', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=331,
)

_SEGMENTREQUEST.fields_by_name['segment_id'].message_type = common__pb2._SEGMENTID
_SEGMENTRESPONSE.fields_by_name['segment'].message_type = common__pb2._SEGMENT
_SEGMENTSRESPONSE.fields_by_name['segments'].message_type = common__pb2._SEGMENTID
_CONFIGUREREQUEST.fields_by_name['tables'].message_type = common__pb2._TABLE
_INSERTREQUEST.fields_by_name['row'].message_type = common__pb2._ROW
DESCRIPTOR.message_types_by_name['SegmentRequest'] = _SEGMENTREQUEST
DESCRIPTOR.message_types_by_name['SegmentResponse'] = _SEGMENTRESPONSE
DESCRIPTOR.message_types_by_name['SegmentsRequest'] = _SEGMENTSREQUEST
DESCRIPTOR.message_types_by_name['SegmentsResponse'] = _SEGMENTSRESPONSE
DESCRIPTOR.message_types_by_name['ConfigureRequest'] = _CONFIGUREREQUEST
DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentRequest = _reflection.GeneratedProtocolMessageType('SegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentRequest)
  })
_sym_db.RegisterMessage(SegmentRequest)

SegmentResponse = _reflection.GeneratedProtocolMessageType('SegmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTRESPONSE,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentResponse)
  })
_sym_db.RegisterMessage(SegmentResponse)

SegmentsRequest = _reflection.GeneratedProtocolMessageType('SegmentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentsRequest)
  })
_sym_db.RegisterMessage(SegmentsRequest)

SegmentsResponse = _reflection.GeneratedProtocolMessageType('SegmentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSRESPONSE,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentsResponse)
  })
_sym_db.RegisterMessage(SegmentsResponse)

ConfigureRequest = _reflection.GeneratedProtocolMessageType('ConfigureRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGUREREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.ConfigureRequest)
  })
_sym_db.RegisterMessage(ConfigureRequest)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)



_PACKER = _descriptor.ServiceDescriptor(
  name='Packer',
  full_name='protos.Packer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=334,
  serialized_end=519,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='protos.Packer.Insert',
    index=0,
    containing_service=None,
    input_type=_INSERTREQUEST,
    output_type=common__pb2._ERROR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Segment',
    full_name='protos.Packer.Segment',
    index=1,
    containing_service=None,
    input_type=_SEGMENTREQUEST,
    output_type=_SEGMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Segments',
    full_name='protos.Packer.Segments',
    index=2,
    containing_service=None,
    input_type=_SEGMENTSREQUEST,
    output_type=_SEGMENTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKER)

DESCRIPTOR.services_by_name['Packer'] = _PACKER

# @@protoc_insertion_point(module_scope)
