# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packer.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='packer.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rpacker.proto\x12\x06protos\x1a\x0c\x63ommon.proto\"h\n\tSegmentId\x12\r\n\x05table\x18\x01 \x01(\t\x12-\n\nresolution\x18\x02 \x01(\x0e\x32\x19.protos.SegmentResolution\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"D\n\x07Segment\x12\x1f\n\x04meta\x18\x01 \x01(\x0b\x32\x11.protos.SegmentId\x12\x18\n\x03Row\x18\x02 \x03(\x0b\x32\x0b.protos.Row\"7\n\x0eSegmentRequest\x12%\n\nsegment_id\x18\x01 \x01(\x0b\x32\x11.protos.SegmentId\"3\n\x0fSegmentResponse\x12 \n\x07segment\x18\x01 \x01(\x0b\x32\x0f.protos.Segment\"8\n\x0fSegmentsRequest\x12%\n\nsegment_id\x18\x01 \x01(\x0b\x32\x11.protos.SegmentId\"7\n\x10SegmentsResponse\x12#\n\x08segments\x18\x02 \x03(\x0b\x32\x11.protos.SegmentId\"1\n\x10\x43onfigureRequest\x12\x1d\n\x06tables\x18\x01 \x03(\x0b\x32\r.protos.Table\"=\n\rInsertRequest\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x18\n\x03row\x18\x02 \x01(\x0b\x32\x0b.protos.Row*&\n\x11SegmentResolution\x12\x08\n\x04HOUR\x10\x00\x12\x07\n\x03\x44\x41Y\x10\x01\x32\xba\x01\n\x07Storage\x12\x30\n\x06Insert\x12\x15.protos.InsertRequest\x1a\r.protos.Error\"\x00\x12<\n\x07Segment\x12\x16.protos.SegmentRequest\x1a\x17.protos.SegmentResponse\"\x00\x12?\n\x08Segments\x12\x17.protos.SegmentsRequest\x1a\x18.protos.SegmentsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_SEGMENTRESOLUTION = _descriptor.EnumDescriptor(
  name='SegmentResolution',
  full_name='protos.SegmentResolution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DAY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=554,
  serialized_end=592,
)
_sym_db.RegisterEnumDescriptor(_SEGMENTRESOLUTION)

SegmentResolution = enum_type_wrapper.EnumTypeWrapper(_SEGMENTRESOLUTION)
HOUR = 0
DAY = 1



_SEGMENTID = _descriptor.Descriptor(
  name='SegmentId',
  full_name='protos.SegmentId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='protos.SegmentId.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='protos.SegmentId.resolution', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protos.SegmentId.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='protos.SegmentId.id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=143,
)


_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='protos.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='protos.Segment.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Row', full_name='protos.Segment.Row', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=213,
)


_SEGMENTREQUEST = _descriptor.Descriptor(
  name='SegmentRequest',
  full_name='protos.SegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='protos.SegmentRequest.segment_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=270,
)


_SEGMENTRESPONSE = _descriptor.Descriptor(
  name='SegmentResponse',
  full_name='protos.SegmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='protos.SegmentResponse.segment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=323,
)


_SEGMENTSREQUEST = _descriptor.Descriptor(
  name='SegmentsRequest',
  full_name='protos.SegmentsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='protos.SegmentsRequest.segment_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=381,
)


_SEGMENTSRESPONSE = _descriptor.Descriptor(
  name='SegmentsResponse',
  full_name='protos.SegmentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='segments', full_name='protos.SegmentsResponse.segments', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=438,
)


_CONFIGUREREQUEST = _descriptor.Descriptor(
  name='ConfigureRequest',
  full_name='protos.ConfigureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tables', full_name='protos.ConfigureRequest.tables', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=489,
)


_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='protos.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='protos.InsertRequest.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row', full_name='protos.InsertRequest.row', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=491,
  serialized_end=552,
)

_SEGMENTID.fields_by_name['resolution'].enum_type = _SEGMENTRESOLUTION
_SEGMENT.fields_by_name['meta'].message_type = _SEGMENTID
_SEGMENT.fields_by_name['Row'].message_type = common__pb2._ROW
_SEGMENTREQUEST.fields_by_name['segment_id'].message_type = _SEGMENTID
_SEGMENTRESPONSE.fields_by_name['segment'].message_type = _SEGMENT
_SEGMENTSREQUEST.fields_by_name['segment_id'].message_type = _SEGMENTID
_SEGMENTSRESPONSE.fields_by_name['segments'].message_type = _SEGMENTID
_CONFIGUREREQUEST.fields_by_name['tables'].message_type = common__pb2._TABLE
_INSERTREQUEST.fields_by_name['row'].message_type = common__pb2._ROW
DESCRIPTOR.message_types_by_name['SegmentId'] = _SEGMENTID
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.message_types_by_name['SegmentRequest'] = _SEGMENTREQUEST
DESCRIPTOR.message_types_by_name['SegmentResponse'] = _SEGMENTRESPONSE
DESCRIPTOR.message_types_by_name['SegmentsRequest'] = _SEGMENTSREQUEST
DESCRIPTOR.message_types_by_name['SegmentsResponse'] = _SEGMENTSRESPONSE
DESCRIPTOR.message_types_by_name['ConfigureRequest'] = _CONFIGUREREQUEST
DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
DESCRIPTOR.enum_types_by_name['SegmentResolution'] = _SEGMENTRESOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentId = _reflection.GeneratedProtocolMessageType('SegmentId', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTID,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentId)
  })
_sym_db.RegisterMessage(SegmentId)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.Segment)
  })
_sym_db.RegisterMessage(Segment)

SegmentRequest = _reflection.GeneratedProtocolMessageType('SegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentRequest)
  })
_sym_db.RegisterMessage(SegmentRequest)

SegmentResponse = _reflection.GeneratedProtocolMessageType('SegmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTRESPONSE,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentResponse)
  })
_sym_db.RegisterMessage(SegmentResponse)

SegmentsRequest = _reflection.GeneratedProtocolMessageType('SegmentsRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentsRequest)
  })
_sym_db.RegisterMessage(SegmentsRequest)

SegmentsResponse = _reflection.GeneratedProtocolMessageType('SegmentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTSRESPONSE,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentsResponse)
  })
_sym_db.RegisterMessage(SegmentsResponse)

ConfigureRequest = _reflection.GeneratedProtocolMessageType('ConfigureRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGUREREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.ConfigureRequest)
  })
_sym_db.RegisterMessage(ConfigureRequest)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'packer_pb2'
  # @@protoc_insertion_point(class_scope:protos.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)



_STORAGE = _descriptor.ServiceDescriptor(
  name='Storage',
  full_name='protos.Storage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=595,
  serialized_end=781,
  methods=[
  _descriptor.MethodDescriptor(
    name='Insert',
    full_name='protos.Storage.Insert',
    index=0,
    containing_service=None,
    input_type=_INSERTREQUEST,
    output_type=common__pb2._ERROR,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Segment',
    full_name='protos.Storage.Segment',
    index=1,
    containing_service=None,
    input_type=_SEGMENTREQUEST,
    output_type=_SEGMENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Segments',
    full_name='protos.Storage.Segments',
    index=2,
    containing_service=None,
    input_type=_SEGMENTSREQUEST,
    output_type=_SEGMENTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGE)

DESCRIPTOR.services_by_name['Storage'] = _STORAGE

# @@protoc_insertion_point(module_scope)
