// This file is generated by rust-protobuf 2.14.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `coordinator.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_14_0;

#[derive(PartialEq,Clone,Default)]
pub struct Node {
    // message fields
    pub nodeType: NodeType,
    pub host: ::std::string::String,
    pub configuration: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Node {
    fn default() -> &'a Node {
        <Node as ::protobuf::Message>::default_instance()
    }
}

impl Node {
    pub fn new() -> Node {
        ::std::default::Default::default()
    }

    // .protos.NodeType nodeType = 1;


    pub fn get_nodeType(&self) -> NodeType {
        self.nodeType
    }
    pub fn clear_nodeType(&mut self) {
        self.nodeType = NodeType::INDEXER;
    }

    // Param is passed by value, moved
    pub fn set_nodeType(&mut self, v: NodeType) {
        self.nodeType = v;
    }

    // string host = 2;


    pub fn get_host(&self) -> &str {
        &self.host
    }
    pub fn clear_host(&mut self) {
        self.host.clear();
    }

    // Param is passed by value, moved
    pub fn set_host(&mut self, v: ::std::string::String) {
        self.host = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_host(&mut self) -> &mut ::std::string::String {
        &mut self.host
    }

    // Take field
    pub fn take_host(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.host, ::std::string::String::new())
    }

    // string configuration = 3;


    pub fn get_configuration(&self) -> &str {
        &self.configuration
    }
    pub fn clear_configuration(&mut self) {
        self.configuration.clear();
    }

    // Param is passed by value, moved
    pub fn set_configuration(&mut self, v: ::std::string::String) {
        self.configuration = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_configuration(&mut self) -> &mut ::std::string::String {
        &mut self.configuration
    }

    // Take field
    pub fn take_configuration(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.configuration, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Node {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.nodeType, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.host)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.configuration)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.nodeType != NodeType::INDEXER {
            my_size += ::protobuf::rt::enum_size(1, self.nodeType);
        }
        if !self.host.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.host);
        }
        if !self.configuration.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.configuration);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.nodeType != NodeType::INDEXER {
            os.write_enum(1, self.nodeType.value())?;
        }
        if !self.host.is_empty() {
            os.write_string(2, &self.host)?;
        }
        if !self.configuration.is_empty() {
            os.write_string(3, &self.configuration)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Node {
        Node::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<NodeType>>(
                    "nodeType",
                    |m: &Node| { &m.nodeType },
                    |m: &mut Node| { &mut m.nodeType },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "host",
                    |m: &Node| { &m.host },
                    |m: &mut Node| { &mut m.host },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "configuration",
                    |m: &Node| { &m.configuration },
                    |m: &mut Node| { &mut m.configuration },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<Node>(
                    "Node",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static Node {
        static mut instance: ::protobuf::lazy::Lazy<Node> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(Node::new)
        }
    }
}

impl ::protobuf::Clear for Node {
    fn clear(&mut self) {
        self.nodeType = NodeType::INDEXER;
        self.host.clear();
        self.configuration.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Node {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Node {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct NodeRequest {
    // message fields
    pub node: ::protobuf::SingularPtrField<Node>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a NodeRequest {
    fn default() -> &'a NodeRequest {
        <NodeRequest as ::protobuf::Message>::default_instance()
    }
}

impl NodeRequest {
    pub fn new() -> NodeRequest {
        ::std::default::Default::default()
    }

    // .protos.Node node = 1;


    pub fn get_node(&self) -> &Node {
        self.node.as_ref().unwrap_or_else(|| Node::default_instance())
    }
    pub fn clear_node(&mut self) {
        self.node.clear();
    }

    pub fn has_node(&self) -> bool {
        self.node.is_some()
    }

    // Param is passed by value, moved
    pub fn set_node(&mut self, v: Node) {
        self.node = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_node(&mut self) -> &mut Node {
        if self.node.is_none() {
            self.node.set_default();
        }
        self.node.as_mut().unwrap()
    }

    // Take field
    pub fn take_node(&mut self) -> Node {
        self.node.take().unwrap_or_else(|| Node::new())
    }
}

impl ::protobuf::Message for NodeRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.node {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.node)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.node.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.node.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> NodeRequest {
        NodeRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Node>>(
                    "node",
                    |m: &NodeRequest| { &m.node },
                    |m: &mut NodeRequest| { &mut m.node },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<NodeRequest>(
                    "NodeRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static NodeRequest {
        static mut instance: ::protobuf::lazy::Lazy<NodeRequest> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(NodeRequest::new)
        }
    }
}

impl ::protobuf::Clear for NodeRequest {
    fn clear(&mut self) {
        self.node.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for NodeRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for NodeRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DiscoverResponse {
    // message fields
    pub nodes: ::protobuf::RepeatedField<Node>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DiscoverResponse {
    fn default() -> &'a DiscoverResponse {
        <DiscoverResponse as ::protobuf::Message>::default_instance()
    }
}

impl DiscoverResponse {
    pub fn new() -> DiscoverResponse {
        ::std::default::Default::default()
    }

    // repeated .protos.Node nodes = 1;


    pub fn get_nodes(&self) -> &[Node] {
        &self.nodes
    }
    pub fn clear_nodes(&mut self) {
        self.nodes.clear();
    }

    // Param is passed by value, moved
    pub fn set_nodes(&mut self, v: ::protobuf::RepeatedField<Node>) {
        self.nodes = v;
    }

    // Mutable pointer to the field.
    pub fn mut_nodes(&mut self) -> &mut ::protobuf::RepeatedField<Node> {
        &mut self.nodes
    }

    // Take field
    pub fn take_nodes(&mut self) -> ::protobuf::RepeatedField<Node> {
        ::std::mem::replace(&mut self.nodes, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for DiscoverResponse {
    fn is_initialized(&self) -> bool {
        for v in &self.nodes {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.nodes)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.nodes {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.nodes {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DiscoverResponse {
        DiscoverResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Node>>(
                    "nodes",
                    |m: &DiscoverResponse| { &m.nodes },
                    |m: &mut DiscoverResponse| { &mut m.nodes },
                ));
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<DiscoverResponse>(
                    "DiscoverResponse",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DiscoverResponse {
        static mut instance: ::protobuf::lazy::Lazy<DiscoverResponse> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(DiscoverResponse::new)
        }
    }
}

impl ::protobuf::Clear for DiscoverResponse {
    fn clear(&mut self) {
        self.nodes.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DiscoverResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DiscoverResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DiscoverRequest {
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DiscoverRequest {
    fn default() -> &'a DiscoverRequest {
        <DiscoverRequest as ::protobuf::Message>::default_instance()
    }
}

impl DiscoverRequest {
    pub fn new() -> DiscoverRequest {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for DiscoverRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DiscoverRequest {
        DiscoverRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let fields = ::std::vec::Vec::new();
                ::protobuf::reflect::MessageDescriptor::new_pb_name::<DiscoverRequest>(
                    "DiscoverRequest",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static DiscoverRequest {
        static mut instance: ::protobuf::lazy::Lazy<DiscoverRequest> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            instance.get(DiscoverRequest::new)
        }
    }
}

impl ::protobuf::Clear for DiscoverRequest {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DiscoverRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DiscoverRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum NodeType {
    INDEXER = 0,
    PACKER = 1,
    COORDINATOR = 2,
}

impl ::protobuf::ProtobufEnum for NodeType {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<NodeType> {
        match value {
            0 => ::std::option::Option::Some(NodeType::INDEXER),
            1 => ::std::option::Option::Some(NodeType::PACKER),
            2 => ::std::option::Option::Some(NodeType::COORDINATOR),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [NodeType] = &[
            NodeType::INDEXER,
            NodeType::PACKER,
            NodeType::COORDINATOR,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                ::protobuf::reflect::EnumDescriptor::new_pb_name::<NodeType>("NodeType", file_descriptor_proto())
            })
        }
    }
}

impl ::std::marker::Copy for NodeType {
}

impl ::std::default::Default for NodeType {
    fn default() -> Self {
        NodeType::INDEXER
    }
}

impl ::protobuf::reflect::ProtobufValue for NodeType {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(self.descriptor())
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11coordinator.proto\x12\x06protos\x1a\x0ccommon.proto\"n\n\x04Node\
    \x12,\n\x08nodeType\x18\x01\x20\x01(\x0e2\x10.protos.NodeTypeR\x08nodeTy\
    pe\x12\x12\n\x04host\x18\x02\x20\x01(\tR\x04host\x12$\n\rconfiguration\
    \x18\x03\x20\x01(\tR\rconfiguration\"/\n\x0bNodeRequest\x12\x20\n\x04nod\
    e\x18\x01\x20\x01(\x0b2\x0c.protos.NodeR\x04node\"6\n\x10DiscoverRespons\
    e\x12\"\n\x05nodes\x18\x01\x20\x03(\x0b2\x0c.protos.NodeR\x05nodes\"\x11\
    \n\x0fDiscoverRequest*4\n\x08NodeType\x12\x0b\n\x07INDEXER\x10\0\x12\n\n\
    \x06PACKER\x10\x01\x12\x0f\n\x0bCOORDINATOR\x10\x022\x80\x01\n\x0bCoordi\
    nator\x12?\n\x08Discover\x12\x17.protos.DiscoverRequest\x1a\x18.protos.D\
    iscoverResponse\"\0\x120\n\x08Register\x12\x13.protos.NodeRequest\x1a\r.\
    protos.Error\"\0J\xfd\x05\n\x06\x12\x04\0\0!\x01\n\x08\n\x01\x0c\x12\x03\
    \0\0\x12\n\x08\n\x01\x02\x12\x03\x02\x08\x0e\n\t\n\x02\x03\0\x12\x03\x04\
    \x07\x15\n\n\n\x02\x05\0\x12\x04\x06\0\n\x01\n\n\n\x03\x05\0\x01\x12\x03\
    \x06\x05\r\n\x0b\n\x04\x05\0\x02\0\x12\x03\x07\x04\x10\n\x0c\n\x05\x05\0\
    \x02\0\x01\x12\x03\x07\x04\x0b\n\x0c\n\x05\x05\0\x02\0\x02\x12\x03\x07\
    \x0e\x0f\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x08\x04\x0f\n\x0c\n\x05\x05\0\
    \x02\x01\x01\x12\x03\x08\x04\n\n\x0c\n\x05\x05\0\x02\x01\x02\x12\x03\x08\
    \r\x0e\n\x0b\n\x04\x05\0\x02\x02\x12\x03\t\x04\x14\n\x0c\n\x05\x05\0\x02\
    \x02\x01\x12\x03\t\x04\x0f\n\x0c\n\x05\x05\0\x02\x02\x02\x12\x03\t\x12\
    \x13\n\n\n\x02\x04\0\x12\x04\x0c\0\x10\x01\n\n\n\x03\x04\0\x01\x12\x03\
    \x0c\x08\x0c\n\x0b\n\x04\x04\0\x02\0\x12\x03\r\x04\x1a\n\r\n\x05\x04\0\
    \x02\0\x04\x12\x04\r\x04\x0c\x0e\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\r\
    \x04\x0c\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\r\r\x15\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\r\x18\x19\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0e\x04\
    \x14\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x0e\x04\r\x1a\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\x0e\x04\n\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x0e\
    \x0b\x0f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0e\x12\x13\n\x0b\n\x04\
    \x04\0\x02\x02\x12\x03\x0f\x04\x1d\n\r\n\x05\x04\0\x02\x02\x04\x12\x04\
    \x0f\x04\x0e\x14\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x0f\x04\n\n\x0c\n\
    \x05\x04\0\x02\x02\x01\x12\x03\x0f\x0b\x18\n\x0c\n\x05\x04\0\x02\x02\x03\
    \x12\x03\x0f\x1b\x1c\n\n\n\x02\x04\x01\x12\x04\x12\0\x14\x01\n\n\n\x03\
    \x04\x01\x01\x12\x03\x12\x08\x13\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x13\
    \x04\x12\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x13\x04\x12\x15\n\x0c\n\x05\
    \x04\x01\x02\0\x06\x12\x03\x13\x04\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\
    \x03\x13\t\r\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x13\x10\x11\n\n\n\x02\
    \x04\x02\x12\x04\x16\0\x18\x01\n\n\n\x03\x04\x02\x01\x12\x03\x16\x08\x18\
    \n\x0b\n\x04\x04\x02\x02\0\x12\x03\x17\x04\x1c\n\x0c\n\x05\x04\x02\x02\0\
    \x04\x12\x03\x17\x04\x0c\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03\x17\r\x11\
    \n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x17\x12\x17\n\x0c\n\x05\x04\x02\
    \x02\0\x03\x12\x03\x17\x1a\x1b\n\n\n\x02\x04\x03\x12\x04\x1a\0\x1b\x01\n\
    \n\n\x03\x04\x03\x01\x12\x03\x1a\x08\x17\n\n\n\x02\x06\0\x12\x04\x1d\0!\
    \x01\n\n\n\x03\x06\0\x01\x12\x03\x1d\x08\x13\n\x0b\n\x04\x06\0\x02\0\x12\
    \x03\x1e\x04?\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x1e\x08\x10\n\x0c\n\
    \x05\x06\0\x02\0\x02\x12\x03\x1e\x11\x20\n\x0c\n\x05\x06\0\x02\0\x03\x12\
    \x03\x1e+;\n\x0b\n\x04\x06\0\x02\x01\x12\x03\x1f\x040\n\x0c\n\x05\x06\0\
    \x02\x01\x01\x12\x03\x1f\x08\x10\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\
    \x1f\x11\x1c\n\x0c\n\x05\x06\0\x02\x01\x03\x12\x03\x1f',b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
