# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06protos\"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x88\x01\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x12segment_resolution\x18\x02 \x01(\x0e\x32\x18.protos.Table.Resolution\x12\x14\n\x0csegment_size\x18\x03 \x01(\x04\x12\x0e\n\x06\x66ields\x18\x04 \x03(\t\"\x15\n\nResolution\x12\x07\n\x03\x44\x41Y\x10\x00\"&\n\x03Row\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"r\n\tSegmentId\x12\r\n\x05table\x18\x01 \x01(\t\x12-\n\nresolution\x18\x02 \x01(\x0e\x32\x19.protos.SegmentResolution\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x14\n\x0cpartition_id\x18\x04 \x01(\t\"D\n\x07Segment\x12\x1f\n\x04meta\x18\x01 \x01(\x0b\x32\x11.protos.SegmentId\x12\x18\n\x03Row\x18\x02 \x03(\x0b\x32\x0b.protos.Row*\x1c\n\x11SegmentResolution\x12\x07\n\x03\x44\x41Y\x10\x00\x62\x06proto3'
)

_SEGMENTRESOLUTION = _descriptor.EnumDescriptor(
  name='SegmentResolution',
  full_name='protos.SegmentResolution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DAY', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=429,
  serialized_end=457,
)
_sym_db.RegisterEnumDescriptor(_SEGMENTRESOLUTION)

SegmentResolution = enum_type_wrapper.EnumTypeWrapper(_SEGMENTRESOLUTION)
DAY = 0


_TABLE_RESOLUTION = _descriptor.EnumDescriptor(
  name='Resolution',
  full_name='protos.Table.Resolution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DAY', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=180,
  serialized_end=201,
)
_sym_db.RegisterEnumDescriptor(_TABLE_RESOLUTION)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='protos.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protos.Error.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='protos.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=62,
)


_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='protos.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protos.Table.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_resolution', full_name='protos.Table.segment_resolution', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segment_size', full_name='protos.Table.segment_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='protos.Table.fields', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TABLE_RESOLUTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=201,
)


_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='protos.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protos.Row.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='protos.Row.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=241,
)


_SEGMENTID = _descriptor.Descriptor(
  name='SegmentId',
  full_name='protos.SegmentId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='protos.SegmentId.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='protos.SegmentId.resolution', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protos.SegmentId.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partition_id', full_name='protos.SegmentId.partition_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=357,
)


_SEGMENT = _descriptor.Descriptor(
  name='Segment',
  full_name='protos.Segment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='protos.Segment.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Row', full_name='protos.Segment.Row', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=427,
)

_TABLE.fields_by_name['segment_resolution'].enum_type = _TABLE_RESOLUTION
_TABLE_RESOLUTION.containing_type = _TABLE
_SEGMENTID.fields_by_name['resolution'].enum_type = _SEGMENTRESOLUTION
_SEGMENT.fields_by_name['meta'].message_type = _SEGMENTID
_SEGMENT.fields_by_name['Row'].message_type = _ROW
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['Row'] = _ROW
DESCRIPTOR.message_types_by_name['SegmentId'] = _SEGMENTID
DESCRIPTOR.message_types_by_name['Segment'] = _SEGMENT
DESCRIPTOR.enum_types_by_name['SegmentResolution'] = _SEGMENTRESOLUTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:protos.Error)
  })
_sym_db.RegisterMessage(Error)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), {
  'DESCRIPTOR' : _TABLE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:protos.Table)
  })
_sym_db.RegisterMessage(Table)

Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), {
  'DESCRIPTOR' : _ROW,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:protos.Row)
  })
_sym_db.RegisterMessage(Row)

SegmentId = _reflection.GeneratedProtocolMessageType('SegmentId', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTID,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:protos.SegmentId)
  })
_sym_db.RegisterMessage(SegmentId)

Segment = _reflection.GeneratedProtocolMessageType('Segment', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:protos.Segment)
  })
_sym_db.RegisterMessage(Segment)


# @@protoc_insertion_point(module_scope)
